import { GoogleGenAI } from "@google/genai";
import { GEMINI_API_KEY, GEMINI_MODEL } from "./envConfig";

const apiKey = GEMINI_API_KEY || process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.warn(
    "⚠️ Warning: GEMINI_API_KEY is not set in environment variables. Gemini API requests will fail until key is configured."
  );
}

/**
 * Initialized Google Gen AI SDK client instance
 */
export const ai = new GoogleGenAI({
  apiKey: apiKey || "",
});

/**
 * List of available Gemini Flash models
 */
export const GEMINI_FLASH_MODELS = {
  GEMINI_2_5_FLASH: "gemini-2.5-flash",
  GEMINI_2_0_FLASH: "gemini-2.0-flash",
  GEMINI_2_0_FLASH_LITE: "gemini-2.0-flash-lite",
  GEMINI_1_5_FLASH: "gemini-1.5-flash",
  GEMINI_1_5_FLASH_8B: "gemini-1.5-flash-8b",
  GEMINI_3_6_FLASH: "gemini-3.6-flash",
  GEMINI_3_5_FLASH: "gemini-3.5-flash",
  GEMINI_3_5_FLASH_LITE: "gemini-3.5-flash-lite",
  GEMINI_3_8_FLASH: "gemini-3.8-flash",
  GEMINI_3_7_FLASH: "gemini-3.7-flash",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

/**
 * Fallback order for Gemini models if primary model is unavailable or rate-limited
 */
export const FALLBACK_MODEL_LIST = [
  GEMINI_FLASH_MODELS.GEMINI_2_5_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_2_0_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_2_0_FLASH_LITE,
  GEMINI_FLASH_MODELS.GEMINI_1_5_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_1_5_FLASH_8B,
  GEMINI_FLASH_MODELS.GEMINI_3_6_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_5_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_5_FLASH_LITE,
  GEMINI_FLASH_MODELS.GEMINI_3_8_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_7_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_3_FLASH_PREVIEW,
];

/**
 * Default Gemini model used across the backend
 */
export const DEFAULT_GEMINI_MODEL =
  GEMINI_MODEL || GEMINI_FLASH_MODELS.GEMINI_2_5_FLASH;

export interface GenerateGeminiContentOptions {
  contents?: string | any[];
  model?: string;
  systemInstruction?: string;
  config?: Record<string, any>;
}

/**
 * Reusable function to generate content with automatic model fallback loop.
 * If the primary model fails or is unavailable, it automatically retries with the next model.
 * 
 * @param {GenerateGeminiContentOptions} options - Function options
 * @returns {Promise<any>} Text or parsed JSON output generated by Gemini
 */
export const generateGeminiContent = async ({
  contents,
  model = DEFAULT_GEMINI_MODEL,
  systemInstruction,
  config,
}: GenerateGeminiContentOptions = {}): Promise<any> => {
  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is missing. Please set GEMINI_API_KEY in your .env file."
    );
  }

  // Create an ordered, unique list of models starting with requested model
  const modelsToTry = Array.from(
    new Set([model, DEFAULT_GEMINI_MODEL, ...FALLBACK_MODEL_LIST])
  ).filter(Boolean);
  const errors: Array<{ model: string; error: string }> = [];

  for (const currentModel of modelsToTry) {
    try {
      const requestOptions: any = {
        model: currentModel,
        contents,
        config: {
          ...(systemInstruction ? { systemInstruction } : {}),
          ...config,
        },
      };

      const response = await ai.models.generateContent(requestOptions);
      const text = response.text || "";
      try {
        const cleanedText = text
          .replace(/^```json\s*/i, "")
          .replace(/^```\s*/i, "")
          .replace(/\s*```$/, "")
          .trim();
        return JSON.parse(cleanedText);
      } catch {
        return text;
      }
    } catch (error: any) {
      console.warn(
        `⚠️ [Gemini Model ${currentModel} Failed]: ${
          error?.message || error
        }. Attempting next fallback model...`
      );
      errors.push({
        model: currentModel,
        error: error?.message || String(error),
      });
    }
  }

  // If all models in loop fail
  const errorDetails = errors.map((e) => `[${e.model}: ${e.error}]`).join(", ");
  console.error(`❌ [Gemini Error]: All models failed. Details: ${errorDetails}`);
  throw new Error(
    `All Gemini Flash models failed. Attempted models: ${modelsToTry.join(", ")}`
  );
};

export default generateGeminiContent;
