/**
 * JurisAI Core AI Configuration
 * 
 * [AI FEATURE: Multi-Model Resiliency & Auto-Fallback Cascade]
 * Provides initialized Google Gen AI SDK client and multi-model fallback execution
 * loops with per-call timeouts and lightweight File API / Context Caching support.
 */
import fs from "fs";
import path from "path";
import { GoogleGenAI } from "@google/genai";
import { GEMINI_API_KEY, GEMINI_MODEL } from "./envConfig";

const apiKey = GEMINI_API_KEY || process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.warn(
    "⚠️ Warning: GEMINI_API_KEY is not set in environment variables. Gemini API requests will fail until key is configured."
  );
}

/**
 * Initialized Google Gen AI SDK client instance
 */
export const ai = new GoogleGenAI({
  apiKey: apiKey || "",
});

/**
 * List of available Gemini Flash models
 */
export const GEMINI_FLASH_MODELS = {
  GEMINI_2_5_FLASH: "gemini-2.5-flash",
  GEMINI_2_0_FLASH: "gemini-2.0-flash",
  GEMINI_2_0_FLASH_LITE: "gemini-2.0-flash-lite",
  GEMINI_1_5_FLASH: "gemini-1.5-flash",
  GEMINI_1_5_FLASH_8B: "gemini-1.5-flash-8b",
  GEMINI_3_6_FLASH: "gemini-3.6-flash",
  GEMINI_3_5_FLASH: "gemini-3.5-flash",
  GEMINI_3_5_FLASH_LITE: "gemini-3.5-flash-lite",
  GEMINI_3_8_FLASH: "gemini-3.8-flash",
  GEMINI_3_7_FLASH: "gemini-3.7-flash",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

/**
 * Capped fallback order for Gemini models (max 3 candidates for fast failure)
 */
export const FALLBACK_MODEL_LIST = [
  GEMINI_FLASH_MODELS.GEMINI_2_5_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_2_0_FLASH,
  GEMINI_FLASH_MODELS.GEMINI_1_5_FLASH,
];

/**
 * Maximum model candidates tried in a single fallback loop
 */
export const MAX_FALLBACK_CANDIDATES = 3;

/**
 * Default Gemini model used across the backend
 */
export const DEFAULT_GEMINI_MODEL =
  GEMINI_MODEL || GEMINI_FLASH_MODELS.GEMINI_2_5_FLASH;

export interface GenerateGeminiContentOptions {
  contents?: string | any[];
  model?: string;
  systemInstruction?: string;
  maxOutputTokens?: number;
  cachedContent?: string;
  config?: Record<string, any>;
  timeoutMs?: number;
}

/**
 * Reusable function to generate content with automatic model fallback loop.
 * If the primary model fails or is unavailable, it automatically retries with up to 3 candidate models.
 * 
 * @param {GenerateGeminiContentOptions} options - Function options
 * @returns {Promise<any>} Text or parsed JSON output generated by Gemini
 */
export const generateGeminiContent = async ({
  contents,
  model = DEFAULT_GEMINI_MODEL,
  systemInstruction,
  maxOutputTokens = 4096,
  cachedContent,
  config,
  timeoutMs = 25000,
}: GenerateGeminiContentOptions = {}): Promise<any> => {
  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is missing. Please set GEMINI_API_KEY in your .env file."
    );
  }

  // Create an ordered, unique list capped at 3 candidate models max to fail fast
  const modelsToTry = Array.from(
    new Set([model, DEFAULT_GEMINI_MODEL, ...FALLBACK_MODEL_LIST])
  )
    .filter(Boolean)
    .slice(0, MAX_FALLBACK_CANDIDATES);

  const errors: Array<{ model: string; error: string }> = [];

  for (const currentModel of modelsToTry) {
    try {
      const requestOptions: any = {
        model: currentModel,
        contents,
        config: {
          ...(systemInstruction ? { systemInstruction } : {}),
          ...(maxOutputTokens ? { maxOutputTokens } : {}),
          ...(cachedContent ? { cachedContent } : {}),
          ...config,
        },
      };

      // Add per-call execution timeout to prevent hanging requests
      let timeoutId: NodeJS.Timeout | null = null;
      const timeoutPromise = new Promise((_, reject) => {
        timeoutId = setTimeout(
          () => reject(new Error(`Model request timed out after ${timeoutMs}ms`)),
          timeoutMs
        );
      });

      try {
        const response: any = await Promise.race([
          ai.models.generateContent(requestOptions),
          timeoutPromise,
        ]);

        if (timeoutId) clearTimeout(timeoutId);

        const text = response.text || "";
        try {
          const cleanedText = text
            .replace(/^```json\s*/i, "")
            .replace(/^```\s*/i, "")
            .replace(/\s*```$/, "")
            .trim();
          return JSON.parse(cleanedText);
        } catch {
          return text;
        }
      } finally {
        if (timeoutId) clearTimeout(timeoutId);
      }
    } catch (error: any) {
      console.warn(
        `⚠️ [Gemini Model ${currentModel} Failed]: ${
          error?.message || error
        }. Attempting next fallback model...`
      );
      errors.push({
        model: currentModel,
        error: error?.message || String(error),
      });
    }
  }

  // If all models in loop fail
  const errorDetails = errors.map((e) => `[${e.model}: ${e.error}]`).join(", ");
  console.error(`❌ [Gemini Error]: All models failed. Details: ${errorDetails}`);
  throw new Error(
    `Gemini model execution failed after ${modelsToTry.length} attempts. Details: ${errorDetails}`
  );
};

/**
 * Helper to upload a file to Gemini's File API instead of inlining base64.
 * Returns URI, mimeType, and name for referencing in generation requests.
 */
export async function uploadGeminiFile(
  fileBuffer: Buffer,
  mimeType: string,
  fileName: string
): Promise<{ uri: string; mimeType: string; name: string } | null> {
  try {
    const tmpDir = path.join(process.cwd(), ".tmp");
    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }
    const safeName = `${Date.now()}_${fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`;
    const tmpPath = path.join(tmpDir, safeName);
    fs.writeFileSync(tmpPath, fileBuffer);

    try {
      const uploadResp = await (ai.files as any).upload({
        file: tmpPath,
        config: { mimeType },
      });

      if (fs.existsSync(tmpPath)) {
        try { fs.unlinkSync(tmpPath); } catch {}
      }

      if (uploadResp?.uri && uploadResp?.name) {
        return {
          uri: uploadResp.uri,
          mimeType: uploadResp.mimeType || mimeType,
          name: uploadResp.name,
        };
      }
    } catch (uploadErr) {
      if (fs.existsSync(tmpPath)) {
        try { fs.unlinkSync(tmpPath); } catch {}
      }
      console.warn("⚠️ Gemini File API upload failed, falling back to inline data:", uploadErr);
    }
  } catch (err) {
    console.warn("⚠️ Temp file creation for Gemini upload failed:", err);
  }
  return null;
}

/**
 * Helper to delete an uploaded file from Gemini File API.
 */
export async function deleteGeminiFile(fileName: string): Promise<void> {
  try {
    if (fileName && (ai.files as any)?.delete) {
      await (ai.files as any).delete({ name: fileName });
    }
  } catch {
    // Ignore cleanup errors
  }
}

/**
 * Helper to create a Gemini Context Cache for static document context.
 */
export async function createGeminiContextCache({
  model = DEFAULT_GEMINI_MODEL,
  systemInstruction,
  contents,
  ttlSeconds = 600,
}: {
  model?: string;
  systemInstruction?: string;
  contents: any[];
  ttlSeconds?: number;
}): Promise<string | null> {
  try {
    if ((ai.caches as any)?.create) {
      const cache = await (ai.caches as any).create({
        model,
        config: {
          systemInstruction,
          contents,
          ttl: `${ttlSeconds}s`,
        },
      });
      return cache?.name || null;
    }
  } catch (err) {
    console.warn("⚠️ Context caching creation bypassed:", (err as any)?.message || err);
  }
  return null;
}

export default generateGeminiContent;
